import type { ClothingItem } from "./store"

export const AESTHETICS = [
  { id: "streetwear", label: "Streetwear", emoji: "🛹" },
  { id: "clean-girl", label: "Clean Girl", emoji: "✨" },
  { id: "grunge", label: "Grunge", emoji: "🖤" },
  { id: "high-fashion", label: "High Fashion", emoji: "💎" },
  { id: "archive", label: "Archive", emoji: "📚" },
  { id: "cottagecore", label: "Cottagecore", emoji: "🌸" },
  { id: "minimalist", label: "Minimalist", emoji: "◻️" },
  { id: "y2k", label: "Y2K", emoji: "💿" },
]

export const VALUES = [
  { id: "local", label: "Local Brands", description: "Support small businesses" },
  { id: "sustainable", label: "Sustainability", description: "Eco-friendly choices" },
  { id: "resale", label: "Resale & Thrift", description: "Pre-loved fashion" },
  { id: "none", label: "No Preference", description: "Show me everything" },
]

export const BUDGET_LABELS = ["Thrift", "Affordable", "Mid-Range", "High Fashion"]

export const SAMPLE_ITEMS: ClothingItem[] = [
  {
    id: "1",
    name: "Oversized Linen Blazer",
    brand: "Everlane",
    price: 178,
    image: "/oversized-cream-linen-blazer-on-model.jpg",
    aesthetic: ["clean-girl", "minimalist"],
    category: "outerwear",
    isSustainable: true,
    description:
      "A relaxed, oversized blazer in breathable linen. Perfect for layering over dresses or pairing with wide-leg trousers.",
    stylingTips: [
      "Layer over a slip dress for evening",
      "Pair with matching trousers for a suit moment",
      "Roll the sleeves for a casual look",
    ],
    pairsWellWith: ["2", "5", "8"],
    recommendationReasons: [
      "Matches your clean-girl aesthetic",
      "Falls within your mid-range budget",
      "Sustainable brand aligns with your values",
    ],
    notRecommendedReasons: [],
    fitInfo: {
      oversized: "Will have an extra relaxed, drapey silhouette",
      relaxed: "Slightly loose with comfortable movement",
      fitted: "May feel too structured for this style",
    },
    sizeGuide: {
      "150-160": "XS/S",
      "160-170": "S/M",
      "170-180": "M/L",
      "180+": "L/XL",
    },
    budgetAlternatives: {
      thrift: "9",
      affordable: null,
      midRange: "1",
      highFashion: null,
    },
  },
  {
    id: "2",
    name: "Vintage Graphic Tee",
    brand: "Local Thrift",
    price: 24,
    image: "/vintage-band-graphic-tee-grunge-style.jpg",
    aesthetic: ["grunge", "streetwear", "y2k"],
    category: "tops",
    isResale: true,
    isLocal: true,
    description: "Authentic vintage band tee with a perfectly worn-in feel. Each piece is one-of-a-kind.",
    stylingTips: ["Tuck into high-waisted jeans", "Layer under a slip dress", "Knot at the waist for cropped look"],
    pairsWellWith: ["3", "6", "10"],
    recommendationReasons: [
      "Thrift find matches your budget",
      "Local brand supports your values",
      "Y2K aesthetic you've been exploring",
    ],
    notRecommendedReasons: [],
    fitInfo: {
      oversized: "Classic boxy vintage fit",
      relaxed: "Slightly cropped when tucked",
      fitted: "Size down for a tighter look",
    },
    sizeGuide: {
      "150-160": "S",
      "160-170": "M",
      "170-180": "L",
      "180+": "XL",
    },
    budgetAlternatives: {
      thrift: "2",
      affordable: "10",
      midRange: null,
      highFashion: null,
    },
  },
  {
    id: "3",
    name: "Wide Leg Pleated Trousers",
    brand: "COS",
    price: 135,
    image: "/wide-leg-pleated-trousers-charcoal-minimalist.jpg",
    aesthetic: ["minimalist", "clean-girl", "high-fashion"],
    category: "bottoms",
    isSustainable: true,
    description:
      "Elegant wide-leg trousers with pressed pleats. A wardrobe essential that transitions from office to evening.",
    stylingTips: ["Pair with a cropped cardigan", "Add a belt to define the waist", "Wear with loafers or heels"],
    pairsWellWith: ["1", "4", "7"],
    recommendationReasons: [
      "Matches your minimalist aesthetic",
      "Falls within your mid-range budget",
      "Sustainable brand aligns with your values",
    ],
    notRecommendedReasons: [],
    fitInfo: {
      oversized: "Will have a slightly relaxed fit",
      relaxed: "Comfortable with a bit of drape",
      fitted: "May feel too tight for this style",
    },
    sizeGuide: {
      "150-160": "XS/S",
      "160-170": "S/M",
      "170-180": "M/L",
      "180+": "L/XL",
    },
    budgetAlternatives: {
      thrift: null,
      affordable: "12",
      midRange: "3",
      highFashion: null,
    },
  },
  {
    id: "4",
    name: "Chunky Platform Loafers",
    brand: "Vagabond",
    price: 165,
    image: "/chunky-black-platform-loafers-shoes.jpg",
    aesthetic: ["grunge", "streetwear", "high-fashion"],
    category: "shoes",
    description: "Statement loafers with a chunky platform sole. Adds edge to any outfit while remaining comfortable.",
    stylingTips: [
      "Pair with ankle socks for preppy look",
      "Great with cropped trousers",
      "Works with both skirts and pants",
    ],
    pairsWellWith: ["3", "6", "9"],
    recommendationReasons: [
      "Matches your grunge aesthetic",
      "Falls within your mid-range budget",
      "High-fashion brand fits your style",
    ],
    notRecommendedReasons: [],
    fitInfo: {
      oversized: "Will fit comfortably",
      relaxed: "May be slightly snug",
      fitted: "Perfectly sized",
    },
    sizeGuide: {
      "150-160": "XS/S",
      "160-170": "S/M",
      "170-180": "M/L",
      "180+": "L/XL",
    },
    budgetAlternatives: {
      thrift: null,
      affordable: null,
      midRange: "4",
      highFashion: null,
    },
  },
  {
    id: "5",
    name: "Silk Midi Slip Dress",
    brand: "Reformation",
    price: 248,
    image: "/silk-slip-dress-champagne-color-elegant.jpg",
    aesthetic: ["clean-girl", "high-fashion", "minimalist"],
    category: "dresses",
    isSustainable: true,
    description: "Effortlessly elegant silk slip dress with a bias cut that flatters every figure.",
    stylingTips: ["Layer with an oversized blazer", "Add a cardigan for modesty", "Dress down with sneakers"],
    pairsWellWith: ["1", "4", "11"],
    recommendationReasons: [
      "Matches your clean-girl aesthetic",
      "Falls within your high-fashion budget",
      "Sustainable brand aligns with your values",
    ],
    notRecommendedReasons: [],
    fitInfo: {
      oversized: "Will have a loose fit",
      relaxed: "Comfortable with a bit of movement",
      fitted: "May feel too tight for this style",
    },
    sizeGuide: {
      "150-160": "XS/S",
      "160-170": "S/M",
      "170-180": "M/L",
      "180+": "L/XL",
    },
    budgetAlternatives: {
      thrift: null,
      affordable: null,
      midRange: null,
      highFashion: "5",
    },
  },
  {
    id: "6",
    name: "Distressed Baggy Jeans",
    brand: "Agolde",
    price: 198,
    image: "/distressed-baggy-jeans-90s-style.jpg",
    aesthetic: ["streetwear", "grunge", "y2k"],
    category: "bottoms",
    description: "Perfectly worn-in baggy jeans with authentic distressing. The ultimate cool-girl denim.",
    stylingTips: [
      "Cuff the hems for a shorter look",
      "Pair with a fitted top for balance",
      "Great with both sneakers and heels",
    ],
    pairsWellWith: ["2", "7", "12"],
    recommendationReasons: [
      "Matches your streetwear aesthetic",
      "Falls within your mid-range budget",
      "Local brand supports your values",
    ],
    notRecommendedReasons: [],
    fitInfo: {
      oversized: "Will have a very relaxed fit",
      relaxed: "Comfortable with some drape",
      fitted: "May feel too tight for this style",
    },
    sizeGuide: {
      "150-160": "XS/S",
      "160-170": "S/M",
      "170-180": "M/L",
      "180+": "L/XL",
    },
    budgetAlternatives: {
      thrift: null,
      affordable: null,
      midRange: "6",
      highFashion: null,
    },
  },
  {
    id: "7",
    name: "Cashmere Crewneck Sweater",
    brand: "Naadam",
    price: 175,
    image: "/cashmere-crewneck-sweater-oatmeal-color.jpg",
    aesthetic: ["clean-girl", "minimalist", "cottagecore"],
    category: "tops",
    isSustainable: true,
    description: "Luxuriously soft cashmere sweater in a versatile oatmeal tone. A forever piece.",
    stylingTips: ["Tuck into trousers", "Layer over collared shirts", "Pair with gold jewelry"],
    pairsWellWith: ["3", "6", "10"],
    recommendationReasons: [
      "Matches your clean-girl aesthetic",
      "Falls within your mid-range budget",
      "Sustainable brand aligns with your values",
    ],
    notRecommendedReasons: [],
    fitInfo: {
      oversized: "Will have a slightly relaxed fit",
      relaxed: "Comfortable with a bit of drape",
      fitted: "May feel too tight for this style",
    },
    sizeGuide: {
      "150-160": "XS/S",
      "160-170": "S/M",
      "170-180": "M/L",
      "180+": "L/XL",
    },
    budgetAlternatives: {
      thrift: null,
      affordable: null,
      midRange: "7",
      highFashion: null,
    },
  },
  {
    id: "8",
    name: "Leather Tote Bag",
    brand: "Madewell",
    price: 188,
    image: "/large-leather-tote-bag-tan-brown.jpg",
    aesthetic: ["clean-girl", "minimalist"],
    category: "accessories",
    description: "Spacious leather tote that gets better with age. Perfect for work and weekend.",
    stylingTips: ["Add a silk scarf for flair", "Use a bag organizer inside", "Let it patina naturally"],
    pairsWellWith: ["1", "5", "7"],
    recommendationReasons: [
      "Matches your clean-girl aesthetic",
      "Falls within your mid-range budget",
      "Minimalist style fits your preferences",
    ],
    notRecommendedReasons: [],
    fitInfo: {
      oversized: "Will have a spacious fit",
      relaxed: "Comfortable with a bit of movement",
      fitted: "May feel too snug for this style",
    },
    sizeGuide: {
      "150-160": "XS/S",
      "160-170": "S/M",
      "170-180": "M/L",
      "180+": "L/XL",
    },
    budgetAlternatives: {
      thrift: null,
      affordable: null,
      midRange: "8",
      highFashion: null,
    },
  },
  {
    id: "9",
    name: "Vintage Denim Jacket",
    brand: "Urban Vintage",
    price: 68,
    image: "/vintage-denim-jacket-worn-faded.jpg",
    aesthetic: ["streetwear", "grunge", "y2k"],
    category: "outerwear",
    isResale: true,
    isLocal: true,
    description: "Authentic vintage Levi's denim jacket with natural fading and character.",
    stylingTips: ["Layer over hoodies", "Pair with slip dresses", "Add pins and patches"],
    pairsWellWith: ["2", "5", "6"],
    recommendationReasons: [
      "Matches your streetwear aesthetic",
      "Falls within your thrift budget",
      "Local brand supports your values",
    ],
    notRecommendedReasons: [],
    fitInfo: {
      oversized: "Will fit comfortably",
      relaxed: "Comfortable with a bit of movement",
      fitted: "May feel too snug for this style",
    },
    sizeGuide: {
      "150-160": "XS/S",
      "160-170": "S/M",
      "170-180": "M/L",
      "180+": "L/XL",
    },
    budgetAlternatives: {
      thrift: "9",
      affordable: null,
      midRange: null,
      highFashion: null,
    },
  },
  {
    id: "10",
    name: "Ribbed Tank Top Set",
    brand: "Skims",
    price: 72,
    image: "/ribbed-tank-top-set-neutral-colors.jpg",
    aesthetic: ["clean-girl", "minimalist", "streetwear"],
    category: "tops",
    description: "Essential ribbed tanks in a 3-pack of neutral tones. The foundation of any wardrobe.",
    stylingTips: ["Layer under everything", "Wear alone with high-waisted bottoms", "Great for layering"],
    pairsWellWith: ["3", "6", "9"],
    recommendationReasons: [
      "Matches your minimalist aesthetic",
      "Falls within your affordable budget",
      "Local brand supports your values",
    ],
    notRecommendedReasons: [],
    fitInfo: {
      oversized: "Will fit comfortably",
      relaxed: "Comfortable with a bit of movement",
      fitted: "May feel too snug for this style",
    },
    sizeGuide: {
      "150-160": "XS/S",
      "160-170": "S/M",
      "170-180": "M/L",
      "180+": "L/XL",
    },
    budgetAlternatives: {
      thrift: null,
      affordable: "10",
      midRange: null,
      highFashion: null,
    },
  },
  {
    id: "11",
    name: "Gold Chain Necklace",
    brand: "Mejuri",
    price: 98,
    image: "/delicate-gold-chain-necklace-jewelry.jpg",
    aesthetic: ["clean-girl", "minimalist", "high-fashion"],
    category: "accessories",
    description: "Delicate gold vermeil chain that layers beautifully or shines on its own.",
    stylingTips: ["Layer with other chains", "Wear alone for minimalist look", "Great with v-necks"],
    pairsWellWith: ["5", "7", "10"],
    recommendationReasons: [
      "Matches your clean-girl aesthetic",
      "Falls within your mid-range budget",
      "High-fashion brand fits your style",
    ],
    notRecommendedReasons: [],
    fitInfo: {
      oversized: "Will fit comfortably",
      relaxed: "Comfortable with a bit of movement",
      fitted: "May feel too snug for this style",
    },
    sizeGuide: {
      "150-160": "XS/S",
      "160-170": "S/M",
      "170-180": "M/L",
      "180+": "L/XL",
    },
    budgetAlternatives: {
      thrift: null,
      affordable: null,
      midRange: null,
      highFashion: "11",
    },
  },
  {
    id: "12",
    name: "Cargo Utility Pants",
    brand: "Carhartt WIP",
    price: 145,
    image: "/cargo-utility-pants-olive-green-streetwear.jpg",
    aesthetic: ["streetwear", "grunge"],
    category: "bottoms",
    description: "Functional cargo pants with utilitarian details. Streetwear staple.",
    stylingTips: ["Pair with crop tops", "Add chunky sneakers", "Roll cuffs to show boots"],
    pairsWellWith: ["2", "9", "10"],
    recommendationReasons: [
      "Matches your streetwear aesthetic",
      "Falls within your mid-range budget",
      "Local brand supports your values",
    ],
    notRecommendedReasons: [],
    fitInfo: {
      oversized: "Will fit comfortably",
      relaxed: "Comfortable with a bit of movement",
      fitted: "May feel too snug for this style",
    },
    sizeGuide: {
      "150-160": "XS/S",
      "160-170": "S/M",
      "170-180": "M/L",
      "180+": "L/XL",
    },
    budgetAlternatives: {
      thrift: null,
      affordable: null,
      midRange: "12",
      highFashion: null,
    },
  },
]

export const OUTFIT_CARDS = [
  {
    id: "outfit-1",
    image: "/minimalist-clean-girl-outfit-white-blazer-beige-pa.jpg",
    aesthetic: "clean-girl",
  },
  {
    id: "outfit-2",
    image: "/grunge-streetwear-outfit-baggy-jeans-band-tee-leat.jpg",
    aesthetic: "grunge",
  },
  {
    id: "outfit-3",
    image: "/high-fashion-editorial-outfit-black-dress-statemen.jpg",
    aesthetic: "high-fashion",
  },
  {
    id: "outfit-4",
    image: "/placeholder.svg?height=500&width=400",
    aesthetic: "streetwear",
  },
  {
    id: "outfit-5",
    image: "/placeholder.svg?height=500&width=400",
    aesthetic: "cottagecore",
  },
  {
    id: "outfit-6",
    image: "/placeholder.svg?height=500&width=400",
    aesthetic: "y2k",
  },
  {
    id: "outfit-7",
    image: "/placeholder.svg?height=500&width=400",
    aesthetic: "minimalist",
  },
  {
    id: "outfit-8",
    image: "/placeholder.svg?height=500&width=400",
    aesthetic: "archive",
  },
]

export const WEEKLY_CHALLENGES = [
  {
    id: "challenge-1",
    title: "The One-Piece Challenge",
    subtitle: "Style this blazer 3 different ways",
    heroItem: "1",
    description: "We picked this piece from your saves. Let's see how many looks you can create.",
    outfitSuggestions: [
      {
        id: "look-1",
        name: "Office Ready",
        items: ["1", "3", "4"],
        description: "Polished and professional",
      },
      {
        id: "look-2",
        name: "Weekend Brunch",
        items: ["1", "6", "10"],
        description: "Casual but put-together",
      },
      {
        id: "look-3",
        name: "Evening Out",
        items: ["1", "5", "11"],
        description: "Elevated for dinner",
      },
    ],
    budgetBreakdown: {
      thrift: 92,
      affordable: 145,
      midRange: 385,
      highFashion: 620,
    },
  },
]

export const STYLE_TRAITS = {
  silhouette: [
    { id: "oversized", label: "Oversized" },
    { id: "relaxed", label: "Relaxed" },
    { id: "fitted", label: "Fitted" },
    { id: "structured", label: "Structured" },
    { id: "flowy", label: "Flowy" },
  ],
  colorPalette: [
    { id: "neutrals", label: "Neutrals" },
    { id: "earth-tones", label: "Earth Tones" },
    { id: "muted", label: "Muted" },
    { id: "bold", label: "Bold" },
    { id: "monochrome", label: "Monochrome" },
  ],
  texture: [
    { id: "linen", label: "Linen" },
    { id: "cashmere", label: "Cashmere" },
    { id: "denim", label: "Denim" },
    { id: "leather", label: "Leather" },
    { id: "silk", label: "Silk" },
    { id: "cotton", label: "Cotton" },
  ],
  patterns: [
    { id: "solid", label: "Solid" },
    { id: "minimal-stripe", label: "Minimal Stripe" },
    { id: "plaid", label: "Plaid" },
    { id: "floral", label: "Floral" },
    { id: "graphic", label: "Graphic" },
  ],
}

export const STYLE_MESSAGES = [
  "Your eye for neutrals is getting sharper",
  "You're building a really cohesive closet",
  "Love how you're mixing high and low pieces",
  "Your layering instincts are evolving beautifully",
  "You've got a signature look forming",
]
